### ISSUE TITLE
Install fails, since no `dist` folder exists yet.

### ISSUE THREAD

**Issue by jpblancoder** [nicoespeon/sass-graph-viz#8]
I get the following error message when installing via npm.
```
➜  npm --version
6.5.0-next.0
➜  npm install -g sass-graph-viz
npm ERR! path /Users/jblanchette/.nvm/versions/node/v11.6.0/lib/node_modules/sass-graph-viz/dist/src/cli.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/jblanchette/.nvm/versions/node/v11.6.0/lib/node_modules/sass-graph-viz/dist/src/cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

I believe this is due to no `dist` folder existing yet.
But in `package.json` you have the following JS files that `npm` is trying to alias.
```
"bin": {
    "sassgraphviz": "dist/src/cli.js",
    "sgv": "dist/src/cli.js"
},
```

**Comment by nicoespeon** [comment]
Oh my… Sometimes, you mess things up. I totally did 🤦‍♂️ 

So, in short: I didn't notice the release was broken because I did `npm link` on my local repo, so everything looked fine—I had a `dist/` folder since I created a build.

The problem was that I didn't put the source files in the released package. Thus, it couldn't build the `dist/` files when installed. So it was basically unusable (except if you did clone the repo and `npm link`).

I fixed the release (using `npm pack` to check the produced package first). I published that under a patch version, so v2.2.1.

And it seems to work now:
![image](https://user-images.githubusercontent.com/1094774/52459131-56226f80-2b31-11e9-8857-40a0a34e9628.png)

Thanks for spotting & telling me. I could have kept releasing broken packages without even noticing.

**Comment by nicoespeon** [comment]
Ok, I closed this too fast. Release is ok but it seems not to be usable as it couldn't find `../package.json`.

This is weird since `tsc` is supposed to include it as part of compilation. It works with local build, but I checked the release build (after you install the package) and it's not present in the `dist/` folder.

Working on it. Looks like I will publish a v2.2.2.

**Comment by nicoespeon** [comment]
Found the last issue. Turns out `package.json` should explicitly be listed in `files` to be included in the `dist/` folder. This was subtle because the file is automatically part of the installed package with npm.

I got it installed & working:
![image](https://user-images.githubusercontent.com/1094774/52460089-a6e89700-2b36-11e9-9f7b-3f5b3f8c3f56.png)

v2.2.2 has been published and you should be able to make the lib work with this.
